Tr 1 sere
widergy/Front-end-training pull request #12
Opened 2023-07-20 16:27 UTC by serelopumo

## Summary

Create list of accounts

## Jira Card

https://widergy.atlassian.net/jira/software/c/projects/TD/boards/130?modal=detail&selectedIssue=TD-74

2023-07-24 12:20 UTC, santicammarano requested changes
Buen trabajo! Te dejo mis sugerencias/correcciones:
- Faltaría el botón para volver del listado de cuentas al home (un botón de back básicamente).
- Revisar el uso de heights y widths en porcentaje. Muchas veces podemos hacer uso de las props de flex para llegar al mismo resultado.
- Revisar el manejo de errores en el componente AccountsList. Que pasa si hay un error en el fetch de las accounts? Handleemos ese caso.
- Recordemos hacer responsive el layout!
<img width="496" alt="image" src="https://github.com/widergy/Front-end-training/assets/102041113/ba078226-d404-4527-a71b-691beaf694c1"> 
<img width="391" alt="image" src="https://github.com/widergy/Front-end-training/assets/102041113/c26d2db3-11e7-4736-9749-8a659c2eadc4">

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  height: 30%;
Dejemos que el div ocupe lo que ocupen sus hijos. No le forcemos un height si no es necesario. En todo caso, aprovechemos las propiedades de grow y shrink de flex para estos casos (o el shorthand flex: 1 por ejemplo, para setear estas props + el flex-basis)

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  justify-content: flex-start;
default value

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  align-content: flex-end;
Cual es el objetivo de esta prop?

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  height: 100%;
Cual es el beneficio de que ocupe todo el height, y no sólo lo que necesita? Dejo una comparación.
<img width="663" alt="image" src="https://github.com/widergy/Front-end-training/assets/102041113/9c70ae47-bddc-4906-abc1-1b311d1490e1">
<img width="662" alt="image" src="https://github.com/widergy/Front-end-training/assets/102041113/595e0246-2b1b-4322-a0b0-3c9ae9761cce">

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  width: 50%;
Podríamos utilizar alguna prop de flex para similar el comportamiento del width?

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +.labelMedidor {
English please 👀

2023-07-24 12:20 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  @extend .labelMedidor;
Acá estamos extendiendo la clase pero reemplazando 2/3 props disponibles. Capaz solamente dejar las props que no reemplazamos declaradas en la clase de la que se hereda, porque el resto no tendría uso.

2023-07-24 14:46 UTC, serelopumo commented on src/app/screens/AccountsList/index.js
> +    dispatch(AccountsActions.getAccounts());
Botón para volver del listado de cuentas al home:
![Captura desde 2023-07-24 10-50-20](https://github.com/widergy/Front-end-training/assets/100161377/91d19bc9-95ed-467e-af42-dc7eafbd476b)

Layout responsive:
![Captura desde 2023-07-24 11-28-10](https://github.com/widergy/Front-end-training/assets/100161377/23960dcc-0c75-46bd-9f1c-5c3c77cd54a3)
![Captura desde 2023-07-24 11-28-44](https://github.com/widergy/Front-end-training/assets/100161377/a94f2fdb-9a67-4b20-bab2-c479138e6b2f)


Validacion y manejo de errores:
![Captura desde 2023-07-24 11-46-22](https://github.com/widergy/Front-end-training/assets/100161377/f9d16904-2844-4864-b58d-0e9f170a5442)

2023-07-24 14:52 UTC, serelopumo commented on src/app/screens/AccountsList/index.js
> +  const objectConfig = {
![Captura desde 2023-07-24 11-52-02](https://github.com/widergy/Front-end-training/assets/100161377/3f077569-60a5-430a-8905-7fe28c33b6ee)

2023-07-24 14:54 UTC, serelopumo commented on src/app/screens/AccountsList/index.js
> +  function capitalize(string) {
![Captura desde 2023-07-24 11-54-30](https://github.com/widergy/Front-end-training/assets/100161377/97d6cde9-9cc9-45fa-989b-95e6a00be337)

2023-07-24 15:01 UTC, serelopumo commented on src/app/screens/AccountsList/index.js
> +                        Medidor {capitalize(account.descripcion_estado)}
![Captura desde 2023-07-24 12-00-38](https://github.com/widergy/Front-end-training/assets/100161377/e316b727-d3d6-4c68-82b7-8f2819f4e362)

2023-07-24 15:04 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +  align-content: flex-end;
cierto! no modifica en nada al comportamiento si no esta

2023-07-24 15:16 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +  width: 50%;
encontre la prop de flex-grow y le puse 0.5 a cada componte
![Captura desde 2023-07-24 12-15-22](https://github.com/widergy/Front-end-training/assets/100161377/378af1ac-8677-4203-9cbe-e865681c517b)

2023-07-24 15:20 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +.labelMedidor {
medidor en ingles es meter?
![Uploading Captura desde 2023-07-24 12-19-59.png…]()

2023-07-24 15:23 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +  @extend .labelMedidor;
cierto! ahora la unica prop que se reemplaza es el color de fondo, el resto comparten las mismas props y se declaran en la clase del medidor
![Captura desde 2023-07-24 12-19-59](https://github.com/widergy/Front-end-training/assets/100161377/9601f071-67cc-412b-a417-403fc0b0a136)

2023-07-25 17:22 UTC, santicammarano requested changes
Genial! Muy buen trabajo. Fijate los últimos comentarios/sugerencias 💪

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +          Back to home
translations

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +  }, []);
Que dependencias deberia tener este useEffect? 🤔

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +              <button
Atomizar en lo posible!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +    dispatch(AccountsActions.getAccounts());
Excelente trabajo!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +  function capitalize(string) {
Genial. Cuando tengamos varios utils de strings por ejemplo, podemos armar un archivo llamado `stringUtils` y colocar todas las funciones que nos sirvan!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +                  {...(account.cuenta_id === currentAccount.cuenta_id
Revisar!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  justify-content: flex-start;
Revisar!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  @extend .labelMedidor;
Nice!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +.labelMedidor {
Yes!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +.labelBaja {
English!

2023-07-25 17:22 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
> +  }, []);
+ en caso de tener un error, deberiamos mostrarlo!

2023-07-25 17:40 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +.cardTittle {
cierto!
![Captura desde 2023-07-25 14-39-40](https://github.com/widergy/Front-end-training/assets/100161377/250cd93a-fee1-4974-9c79-da8cfdde8a45)

2023-07-25 17:45 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +  padding-bottom: 40px;
![Captura desde 2023-07-25 14-44-17](https://github.com/widergy/Front-end-training/assets/100161377/3d153cd9-99d2-40ef-9e25-a1341289b20f)

2023-07-25 17:49 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +  flex-wrap: nowrap;
eliminado!

2023-07-25 17:52 UTC, serelopumo commented on src/app/screens/AccountsList/styles.module.scss
> +  justify-content: flex-start;
cierto! ahi ya lo borre !

2023-07-25 18:11 UTC, serelopumo commented on src/app/screens/AccountsList/index.js
> +                  {...(account.cuenta_id === currentAccount.cuenta_id
perfecto! asi estaria bien?  la clase card no tenia ningun objetivo como dijiste asi que la borre!

![Captura desde 2023-07-25 15-10-43](https://github.com/widergy/Front-end-training/assets/100161377/2823c3cc-47eb-4e70-bfbd-bd22613cb6c4)
![Captura desde 2023-07-25 15-10-43](https://github.com/widergy/Front-end-training/assets/100161377/ed88d81c-4f4a-4bd3-905a-d1b53ea8df55)

2023-07-25 18:45 UTC, serelopumo commented on src/app/screens/AccountsList/index.js
> +              <button
buenisimo! ahora hay un componente dentro del map que se llama AccountCard

![Captura desde 2023-07-25 15-10-59](https://github.com/widergy/Front-end-training/assets/100161377/e3f1d438-3cbd-4c40-9774-8c0efcba8adc)

![Captura desde 2023-07-25 15-44-39](https://github.com/widergy/Front-end-training/assets/100161377/858a12dc-8cf3-4a99-b3bb-5ba8cf948bcb)

2023-07-25 19:42 UTC, santicammarano requested changes

2023-07-25 19:42 UTC, santicammarano commented on src/app/screens/AccountsList/AccountCard/constants.js
> +export const isCurrentAccount = (account, currentAccount) => account.cuenta_id === currentAccount.cuenta_id;
Esta función iria en `utils`

2023-07-25 19:42 UTC, santicammarano commented on src/app/screens/AccountsList/AccountCard/index.js
> +const AccountCard = ({ account, handleClick, currentAccount }) => (
Nice!

2023-07-26 10:56 UTC, santicammarano commented on src/app/screens/AccountsList/AccountCard/index.js
> +            className={objectConfig[account.descripcion_estado.toLowerCase()]}
Just un reminder, el mappeo por estado se hace a través del `estado` y no la `descripcion_estado`. Esto nos permite poder cambiar lo que mostramos (descripcion) sin romper la logica asociada por detras (estado).

2023-07-26 10:57 UTC, santicammarano approved these changes
Excelente trabajo!

2023-07-26 10:57 UTC, closed without merging