TD-67: Web Ejercicio 1
widergy/Front-end-training pull request #13
Opened 2023-07-21 20:28 UTC by alexmarygr

## Screenshots
![Captura desde 2023-07-21 17-23-13](https://github.com/widergy/Front-end-training/assets/30269302/e75200b5-26eb-4269-b70c-b48c7ceb3295)

## Jira Card

[JIRA](https://widergy.atlassian.net/browse/TD-67)

2023-07-24 13:42 UTC, santicammarano requested changes
Muy buen trabajo! 🚀  Te dejo mis comentarios:
- El cliente `idinir` no levanta! Chequear eso.
- Revisar usos innecesarios de varios estilos. A veces, menos es mas!
- Realizar un manejo de errores para el caso que tengamos un `accountsError`.
- Recordar ordenar las props de estilado alfabéticamente.
- Hacerlo responsive! (recordar uso de media querys) 🖼️ 
<img width="445" alt="image" src="https://github.com/widergy/Front-end-training/assets/102041113/20e41d83-088f-4b58-897f-ed826e474ba6">

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  height: calc(100% - #{$topbar-heigth});
Recordemos que el porcentaje que ocupan los componentes es en base al espacio que tienen disponible! (salvo que le indiquemos lo contrario)

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  flex-flow: row nowrap;
default values!

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  justify-content: space-between;
Si content tiene un solo hijo (UTLoading), cual seria el objetivo de esta prop?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +  justify-content: space-around;
Es necesario este, dado que el componente tiene un solo hijo?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/index.js
> +  const stateStyle = descripcionEstado === 'ACTIVO' ? styles.active : styles.inactive;
Que pasa si tenemos 6 estados posibles? Sería esta una lógica escalable para aplicar?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/index.js
> +      <div className={`${accountSelected}`}>
Capaz podríamos tener una clase base para el container, y si se cumple la condicion de que la cuenta es la seleccionada, agregarle otra clase más al estilado del componente.

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/index.js
> +            Medidor conectado
Mostrar el estado real del medidor (`descripcion_estado`)

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  &-current {
Hacerlo en una clase aparte, que solo tenga el background-color 👀

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  position: relative;
Que nos aporta esto? 👀

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  width: 425px;
Este width nos traerá problemas en responsive si no lo manejamos correctamente (probablemente un teléfono tenga menos de 425px de ancho)!

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  justify-content: flex-start;
default value!

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  flex-wrap: wrap;
Que nos aporta `wrap`?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  justify-content: flex-start;
default values!

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +.info {
Las props de height y width utilizadas, son necesarias?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  flex-direction: row;
default values!

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  flex-wrap: wrap;
Que nos aporta `wrap`?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  align-items: flex-end;
Que nos aporta?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/index.js
> +          <UTLabel className={`${styles.state} ${stateStyle}`} variant="small" colorTheme="light">
```suggestion
          <UTLabel className={`${stateStyle}`} variant="small" colorTheme="light">
```
Existe esta clase?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  border: 0.5px solid $white;
Borde blanco en fondo blanco!

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +.stateContainer {
Todas las props de flex para esta clase, son necesarias para lo que queremos conseguir?

2023-07-24 13:42 UTC, santicammarano commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  @extend .stateContainer;
Nice!

2023-07-25 12:53 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  position: relative;
`padding` es necesario porque nos evita que todo esté muy pegado el borde de la card con el texto.

2023-07-25 18:09 UTC, santicammarano requested changes
Buen trabajo y correcciones! 🚀 
- Las cards se estan viendo mal!
<img width="1440" alt="image" src="https://github.com/widergy/Front-end-training/assets/102041113/e7d0ecca-c923-4181-84c4-ffd1c8246802">
- Falta un boton para volver al home desde el listado de cuentas.

2023-07-25 18:09 UTC, santicammarano commented on src/app/screens/AccountsList/styles.module.scss
> +@media #{$desktop} {
![image](https://github.com/widergy/Front-end-training/assets/102041113/cb65e1d9-944c-4911-8e5c-e470bf484f73)
Esta mediaQuery por su definicion no sirve para ajustar el estilado a layouts responsive mobile, por ejemplo. Revisar!

2023-07-25 18:09 UTC, santicammarano commented on src/app/screens/AccountsList/index.js
>    }, []);
Que dependencias le faltarian a este useEffect?

2023-07-26 19:42 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/constants.js
> +  [ACTIVE]: styles.active,
```javascript
const ACTIVE = 'activo';
const INACTIVE = 'inactivo';
const SUSPENDED = 'suspendidoimpago';
const DROP = 'bajaentratamiento';

export const statusVariants = {
  [ACTIVE]: styles.active,
  [INACTIVE]: styles.inactive,
  [SUSPENDED]: styles.suspended,
  [DROP]: styles.drop
};
```

2023-07-26 19:44 UTC, alexmarygr commented on src/app/screens/AccountsList/styles.module.scss
> +@media #{$desktop} {
```javascript
.container {
  ...
  width: 400px;
}

@media #{$tablet-mobile} {
  .container {
    width: 300px;
  }
}
```

2023-07-26 19:46 UTC, alexmarygr commented
> Buen trabajo y correcciones! rocket
> 
> * Las cards se estan viendo mal!
> 
![Captura desde 2023-07-26 16-45-16](https://github.com/widergy/Front-end-training/assets/30269302/6f8f8a2b-5200-4578-8778-88c2f5949c4d)

2023-07-27 13:07 UTC, alexmarygr commented on src/app/screens/AccountsList/index.js
>    }, []);
```javascript
  useEffect(() => {
    if (!accounts.length && !accountsError && !accountsLoading) dispatch(AccountsActions.getAccounts());
  }, [accounts, accountsError, accountsLoading, dispatch]);
```

2023-07-27 13:11 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +.info {
```css
.info {
  align-items: flex-start;
  display: flex;
  flex-direction: column;
  color: $gray;
  padding: 15px;
}
```

2023-07-27 13:14 UTC, alexmarygr commented on src/constants/routes.js
> +export const ACCOUNTS_LIST = '/cuentas_asociadas';
```javascript
export const HOME = '/';
export const BILLS_HISTORY = '/historico_de_facturas';
export const ACCOUNTS_LIST = '/listado_de_cuentas';
```

2023-07-27 13:15 UTC, alexmarygr commented on src/config/segba/texts.js
>      Account: {
**/src/config/idinir/texts.js**
```javascript
export default {
  es: {
    Account: {
      accountNumber: 'Cuenta N°: {{id}}',
      accountOwner: 'Titular',
      accountState: 'Estado',
      accountsListTitle: 'Listado de cuentas',
      measurer: 'Medidor {{descripcionEstado}}'
...
```

2023-07-27 13:16 UTC, alexmarygr commented on src/app/screens/AccountsList/index.js
> +          <div className={styles.account_list}>
```javascript
<UTLoading loading={accountsLoading}>
        {accountsError ? (
          <UTLabel>{accountsError}</UTLabel>
        ) : (
          <div className={styles.accountList}>
            {accounts &&
              accounts.map(account => <AccountItem account={account} currentAccount={currentAccount} />)}
          </div>
        )}
      </UTLoading>
```

2023-07-27 13:17 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  align-items: flex-end;
Con el `justify-content: flex-end;` ya me alcanzaba.

2023-07-27 13:17 UTC, alexmarygr commented on src/app/screens/AccountsList/styles.module.scss
> +.account_list {
```css
.accountList {
  display: flex;
  flex-flow: row wrap;
  grid-gap: 8px;
}
```

2023-07-27 13:19 UTC, alexmarygr commented on src/app/screens/AccountsList/index.js
> +      <div className={styles.content}>
No era necesario `<div className={styles.content}>` así que solo conservé el padre `container`.

2023-07-27 13:19 UTC, alexmarygr commented on src/app/screens/AccountsList/styles.module.scss
> +  height: calc(100% - #{$topbar-heigth});
```css
.container {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-around;
  padding: 40px 20px;
}
```

2023-07-27 13:21 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/index.js
> +  const stateStyle = descripcionEstado === 'ACTIVO' ? styles.active : styles.inactive;
```javascript
import styles from './styles.module.scss';

const ACTIVE = 'activo';
const INACTIVE = 'inactivo';
const SUSPENDED = 'suspendidoimpago';
const DROP = 'bajaentratamiento';

export const statusVariants = {
  [ACTIVE]: styles.active,
  [INACTIVE]: styles.inactive,
  [SUSPENDED]: styles.suspended,
  [DROP]: styles.drop
};
```

2023-07-27 13:22 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  &-current {
```css
.selected {
  @extend .container;
  background-color: $selected-account;
}
```

2023-07-27 13:23 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  width: 425px;
```css
.container {
  display: flex;
  justify-content: flex-start;
  padding: 10px;
  margin: $margin;
  flex-direction: column;
  box-sizing: border-box;
  box-shadow: 1px -2px 3px 3px $shadow-color;
  border-radius: 10px;
  width: 400px;
}

@media #{$tablet-mobile} {
  .container {
    width: 300px;
  }
}
```

2023-07-27 13:24 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +  flex-wrap: wrap;
```css
.info {
  align-items: flex-start;
  display: flex;
  flex-direction: column;
  color: $gray;
  padding: 15px;
}
```

2023-07-27 13:26 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/index.js
> +          <UTLabel className={`${styles.state} ${stateStyle}`} variant="small" colorTheme="light">
```javascript
<UTLabel className={stateStyle} variant="small" colorTheme="light">
            {i18.t('Account:measurer', { descripcionEstado })}
</UTLabel>
```

2023-07-27 13:28 UTC, alexmarygr commented on src/app/screens/AccountsList/components/AccountItem/styles.module.scss
> +.stateContainer {
```css
.stateContainer {
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
  border-radius: 20px;
  padding: 3%;
}
```

2023-07-27 17:06 UTC, santicammarano approved these changes
Excelente trabajo!! 🚀

2023-07-27 17:06 UTC, closed without merging