TD-68: Web ejercicio 2
widergy/Front-end-training pull request #15
Opened 2023-07-26 15:23 UTC by alexmarygr

## Summary
Web: Ejercicio 2

## Screenshots
![Captura desde 2023-07-26 12-21-07](https://github.com/widergy/Front-end-training/assets/30269302/8dea1253-55df-4e6c-80eb-5c5efb5a8f56)
![Captura desde 2023-07-26 12-21-33](https://github.com/widergy/Front-end-training/assets/30269302/0e0955dd-59a0-48af-97e7-dd037b7e67c4)
![Captura desde 2023-07-26 12-22-15](https://github.com/widergy/Front-end-training/assets/30269302/7ac25ae0-a029-4c83-82e0-fd045c6dd8b7)

## Jira Card

[JIRA](https://widergy.atlassian.net/browse/TD-68)

2023-07-27 18:55 UTC, santicammarano requested changes
Genial trabajo, muy bueno todo! Te dejo mis sugerencias/comments:
- Espaciemos los botones un poco! 
![image](https://github.com/widergy/Front-end-training/assets/102041113/91cadecb-6171-4890-9ea6-11daa9364374)
- La fecha no esta formateada!
![image](https://github.com/widergy/Front-end-training/assets/102041113/ac63e306-6749-44a0-b0a8-889d49f3bc9d)

2023-07-27 18:55 UTC, santicammarano commented on src/config/segba/config.js
> +const paymentColumns = [
Genial, pero mejor declararlo como `columns` directamente dentro de un objeto (paymentsHistory por ejemplo) en el objeto que se exporta por defecto. Así se le da semántica:
```
paymentsHistory: {
const paymentColumns = [
columns: [...]
}
```

2023-07-27 18:55 UTC, santicammarano commented on src/app/screens/PaymentsHistory/index.js
> +                container: styles.container,
Podrias llamar igual a las clases y hacer un spread de un objeto con claes, por ejemplo. Asi queda mas limpio esto.

2023-07-27 20:13 UTC, alexmarygr commented on src/app/screens/Home/index.js
> +    if (!payments.length && !paymentsError && !paymentsLoading) dispatch(PaymentsActions.getPayments());
Creo que me confundí y lo puse en ambas. Me fijé y no es necesario en el HOME, en la componente me basta. 😆

2023-07-28 13:25 UTC, santicammarano requested changes
Genial!
- Quedaron desordenados los pagos
![image](https://github.com/widergy/Front-end-training/assets/102041113/c424800d-6aa3-4d9b-8c83-caba2cf28372)

2023-07-28 13:25 UTC, santicammarano commented on src/config/segba/config.js
> +  paymentsHistory: {
Excelente!

2023-07-28 13:25 UTC, santicammarano commented on src/app/screens/PaymentsHistory/utils.js
> +  Number(amount)
Ya nos viene como numero el dato!

2023-07-31 13:00 UTC, santicammarano approved these changes
Nice work!

2023-07-31 13:01 UTC, closed without merging